---
- hosts: packer
  connection: ssh
  become: yes
  vars_files:
    - "vault/{{ vault_environment }}.yml"
  pre_tasks:
    - name: Run sample task and retrieve value from vault
      shell: echo "successfully retrieved {{ sample_key }} for sample_key from vault"
  roles:
    - docker
    - { role: mysql, mysql_docker: 'install_mysql' }
    - { role: nginx, nginx_mode: 'install_nginx' }
